name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        architecture: [x64, ia32, arm64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Build for ${{ matrix.architecture }}
      run: |
        if (${{ matrix.architecture }} -eq "x64") { npm run build:win-x64 }
        elseif (${{ matrix.architecture }} -eq "ia32") { npm run build:win-ia32 }
        elseif (${{ matrix.architecture }} -eq "arm64") { npm run build:win-arm64 }
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: setup-wizard-free-${{ matrix.architecture }}
        path: dist-electron/
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist-electron/*.exe
          dist-electron/*.blockmap
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
